moved TestFactory and WebSocketTests because they weren't working before. Now they at least look better but they're still not working... NoClassDefFoundError? How?